# `torch.tensor` operations

In [19]:
import torch
import numpy as np

# Check if CUDA is available and print information about the device
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Current CUDA device: {torch.cuda.current_device()}")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
    print(f"Device count: {torch.cuda.device_count()}")
    
# Create a simple tensor and demonstrate device movement
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Create a tensor on CPU
cpu_tensor = torch.randn(2, 3)
print(f"CPU tensor device: {cpu_tensor.device}")

# Move tensor to available device
device_tensor = cpu_tensor.to(device)
print(f"Moved tensor device: {device_tensor.device}")
print("CUDA Version: 12.4")

CUDA available: True
Current CUDA device: 0
Device name: NVIDIA GeForce RTX 4070 Laptop GPU
Device count: 1
Using device: cuda
CPU tensor device: cpu
Moved tensor device: cuda:0
CUDA Version: 12.4


In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[ 1.9977e-15,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00,  1.5912e+00]],

        [[ 3.6893e+19,  1.8732e+00, -2.0000e+00],
         [ 1.7064e+00,  1.0842e-19,  1.7735e+00]]])
torch.Size([2, 2, 3])
tensor([[[1.9966e-15, 0.0000e+00, 0.0000e+00],
         [0.0000e+00,        nan, 1.5912e+00]],

        [[1.7753e+28, 4.4339e+27, 1.7975e+19],
         [6.9481e+22, 5.5757e-02, 1.8728e+31]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [6]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [10]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [11]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

# Use matrix multiplication instead of element-wise multiplication
print(a @ b)  # Using the @ operator for matrix multiplication
# Alternative: print(torch.matmul(a, b))

tensor([[0.5365, 0.6050],
        [0.6866, 0.6609]])


In [12]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
# Concatenate along the 0th dimension
result = torch.cat((x, y), dim=0)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [25]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
# Reshape y to match x's shape or use cat instead of stack
# Option 1: Make y have the same shape as x
y_reshaped = torch.tensor([[5, 6], [7, 8]])  # Adding a second row
result = torch.stack((x, y_reshaped), dim=0)
print(result)

# Option 2: Use torch.cat which allows different shapes
result_cat = torch.cat((x, y), dim=0)
print("\nUsing torch.cat instead:")
print(result_cat)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Using torch.cat instead:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [26]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.4491, 0.6265, 0.9411, 0.4922],
        [0.5461, 0.5396, 0.3053, 0.1973]])
tensor([[0.8982, 1.2531, 1.8823, 0.9844],
        [1.0921, 1.0792, 0.6107, 0.3946]])


In [16]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]]])
tensor([[[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]]])
tensor([[[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]]])


In [17]:
a = torch.ones(4, 3, 2)

b = a  torch.rand(4, 3)    # dimensions must match last-to-first

SyntaxError: invalid syntax (3919499683.py, line 3)

In [ ]:
c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (0) at non-singleton dimension 2

In [27]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

92.0 <class 'float'>


In [28]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [29]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [30]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [31]:
n = np.ones(5)
t = torch.from_numpy(n)

In [32]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [35]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Tensor moved to GPU: {tensor.device}")
    print(f"Tensor on GPU: {tensor}")

Tensor moved to GPU: cuda:0
Tensor on GPU: tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]], device='cuda:0')


In [34]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [36]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.3277, 0.5210, 0.7349, 0.7823, 0.8637, 0.1891, 0.3952, 0.9176, 0.8960,
         0.4887, 0.8625, 0.6191, 0.9935, 0.1844, 0.6138, 0.6854, 0.0438, 0.0636,
         0.2884, 0.4362]])
torch.Size([20])
tensor([0.3277, 0.5210, 0.7349, 0.7823, 0.8637, 0.1891, 0.3952, 0.9176, 0.8960,
        0.4887, 0.8625, 0.6191, 0.9935, 0.1844, 0.6138, 0.6854, 0.0438, 0.0636,
        0.2884, 0.4362])
torch.Size([2, 2])
torch.Size([2, 2])


In [37]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]],

        [[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]],

        [[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]],

        [[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]]])


In [38]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.9180, 0.9180],
         [0.7293, 0.7293],
         [0.5351, 0.5351]],

        [[0.9180, 0.9180],
         [0.7293, 0.7293],
         [0.5351, 0.5351]],

        [[0.9180, 0.9180],
         [0.7293, 0.7293],
         [0.5351, 0.5351]],

        [[0.9180, 0.9180],
         [0.7293, 0.7293],
         [0.5351, 0.5351]]])


In [39]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


# Logistic regression with PyTorch

In [40]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import torch
import torch.nn as nn
import torch.optim as optim

import warnings
# filter warnings
warnings.filterwarnings('ignore')

## Data Procesing

In [41]:
# Reading data

df = pd.read_csv('../data/Module_1_Lecture_2_Class_Spaceship_Titanic.csv')
df = df.set_index('PassengerId')

TARGET = 'Transported'
FEATURES = [col for col in df.columns if col != TARGET]

In [42]:
imputer_cols = ["Age", "FoodCourt", "ShoppingMall", "Spa", "VRDeck" ,"RoomService"]
imputer = SimpleImputer(strategy='median')
imputer.fit(df[imputer_cols])
df[imputer_cols] = imputer.transform(df[imputer_cols])

df["HomePlanet"].fillna('Gallifrey', inplace=True)
df["Destination"].fillna('Skaro', inplace=True)

df['CryoSleep_is_missing'] = df['CryoSleep'].isna().astype(int)
df['VIP_is_missing'] = df['VIP'].isna().astype(int)

df["CryoSleep"].fillna(False, inplace=True)
df["VIP"].fillna(False, inplace=True)

df["CryoSleep"] = df["CryoSleep"].astype(int)
df["VIP"] = df["VIP"].astype(int)

dummies = pd.get_dummies(df.loc[:, ['HomePlanet', 'Destination']], dtype=int)

df = pd.concat([df, dummies], axis=1)
df.drop(columns=['HomePlanet', 'Destination'], inplace=True)

df[TARGET] = df[TARGET].astype(int)

df.drop(["Name" ,"Cabin"] , axis=1 ,inplace = True)

In [43]:
# Train/test split

X = df.drop(TARGET , axis =1 ).values
y = df[TARGET].values

X_train , X_test , y_train , y_test = train_test_split(X, y, random_state = 42, test_size =0.33, stratify=y)

In [44]:
# Convert numpy arrays to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

## Layers use-cases

In [45]:
m = nn.Linear(5, 3)
input = torch.randn(4, 5)
output = m(input)

print('Input:', input, f'shape {input.shape}', sep='\n')
print('\nOutput:', output, f'shape {output.shape}', sep='\n')

Input:
tensor([[-0.8357, -0.4161,  1.2908, -2.5644, -0.3617],
        [ 0.7013,  0.9124, -0.5062,  1.0751, -0.8410],
        [-0.1463,  0.7236, -1.9774, -1.1320, -0.1355],
        [ 0.1958,  0.0596, -0.1925, -0.4961, -0.7434]])
shape torch.Size([4, 5])

Output:
tensor([[-0.1850, -0.4793,  0.7841],
        [ 0.6062,  0.3857, -0.7658],
        [ 0.9758, -0.4256,  0.5126],
        [ 0.4023, -0.1335,  0.0320]], grad_fn=<AddmmBackward0>)
shape torch.Size([4, 3])


In [46]:
t = torch.randn(4)
print('Input: ', t)
print('Applying sigmoid: ', torch.sigmoid(t))

Input:  tensor([ 0.7376,  0.6272, -1.6334,  0.9548])
Applying sigmoid:  tensor([0.6765, 0.6519, 0.1634, 0.7221])


## Model

In [47]:
# Define the logistic regression model

class LogisticRegression(nn.Module):
    def __init__(self, input_dim):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_dim, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out

In [67]:
# Instantiate the model
input_dim = X_train.shape[1]
model = LogisticRegression(input_dim)

# Define loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [68]:
model.parameters

<bound method Module.parameters of LogisticRegression(
  (linear): Linear(in_features=18, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>

In [69]:
# Train the model
num_epochs = 50000
model.train()
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs.squeeze(), y_train)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 5 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [5/50000], Loss: 14.6150
Epoch [10/50000], Loss: 14.1413
Epoch [15/50000], Loss: 15.5842
Epoch [20/50000], Loss: 17.5166
Epoch [25/50000], Loss: 18.4994
Epoch [30/50000], Loss: 15.9150
Epoch [35/50000], Loss: 14.5882
Epoch [40/50000], Loss: 13.1879
Epoch [45/50000], Loss: 14.6454
Epoch [50/50000], Loss: 14.6329
Epoch [55/50000], Loss: 12.6497
Epoch [60/50000], Loss: 12.9471
Epoch [65/50000], Loss: 13.0932
Epoch [70/50000], Loss: 12.8824
Epoch [75/50000], Loss: 12.0559
Epoch [80/50000], Loss: 12.4696
Epoch [85/50000], Loss: 12.4063
Epoch [90/50000], Loss: 13.4779
Epoch [95/50000], Loss: 12.3020
Epoch [100/50000], Loss: 11.6563
Epoch [105/50000], Loss: 11.8636
Epoch [110/50000], Loss: 12.3560
Epoch [115/50000], Loss: 11.9014
Epoch [120/50000], Loss: 12.7146
Epoch [125/50000], Loss: 14.7712
Epoch [130/50000], Loss: 14.1438
Epoch [135/50000], Loss: 12.0607
Epoch [140/50000], Loss: 15.5244
Epoch [145/50000], Loss: 12.6426
Epoch [150/50000], Loss: 13.2584
Epoch [155/50000], Loss: 14.81

In [70]:
# Test the model
model.eval()
with torch.no_grad():
    y_pred = model(X_test).squeeze().numpy().round()

accuracy_score(y_test, y_pred)

0.7922621122342279